---
- name: Import the key for the official MongoDB repository
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present

- name: Create list file
  lineinfile: dest=/etc/apt/sources.list.d/mongodb-org-3.0.list line="deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" create=yes

- name: Install mongodb-org package
  apt: name=mongodb-org update_cache=yes force=yes